services:
  jellyfix:
    container_name: jellyfix
    image: safiyu/jellyfinfix:latest
    volumes:
      - /share/Media:/media:rw
    environment:
      - MODE=watch
      - DEBOUNCE_SECONDS=10
      - CRON_STRING=0 */6 * * *
      - TZ=Europe/Paris
    restart: always
    healthcheck:
      disable: false
